### ISSUE TITLE
Doesn't compile with 8.0.1

### ISSUE THREAD

**Issue by wyager** [adamwalker/sdr#4]
`sdr` does not compile with GHC 8.0.1/cabal-install version 1.24.0.0, citing unsatisfiable constraints.

Presumably, for the most part, version numbers just need to be updated.

**Comment by wyager** [comment]
After deleting the cairo stuff, updating dependencies, changing the dependencies on fftw-real, removing imports of Foreign.Storable.Complex, it builds.

https://github.com/adamwalker/sdr/compare/master...wyager:master

**Comment by adamwalker** [comment]
Thanks for the bug report. I've been meaning to update this for a while. Will take a look at it this weekend.

**Comment by adamwalker** [comment]
Should be fixed now

**Comment by wyager** [comment]
Looks good! Builds, at least. Will play around with it soon.

**Comment by wyager** [comment]
Alright, if there's nothing else, closing issue!
